export {default as BottomMenuBar} from './BottomMenuBar'
export {default as FormActivity} from './FormActivity'
export {default as SelectPhotos} from './SelectPhotos'
export {default as FormDone} from './FormDone'
export {default as Viewlocalfiles} from './Viewlocalfiles'